---

- name: install jupyterhub config file
  template: src=jupyterhub_config.py.j2 dest={{jupyterhub_config_dir}}/jupyterhub_config.py owner=root group=root mode=0644
  become: true

- name: install jupyter notebook config file
  template: src=jupyter_notebook_config.py.j2 dest={{jupyter_config_dir}}/jupyter_notebook_config.py owner=root group=root mode=0644
  become: true

- name: install jupyterhub cookie secret
  copy: src="../../../security/cookie_secret" dest={{jupyterhub_srv_dir}}/cookie_secret owner=root group=root mode=0600
  become: true

- name: install jupyter labhub launch script
  template: src=start-jupyter-labhub.sh.j2 dest=/usr/local/bin/start-jupyter-labhub.sh mode=0777
  become: true
